#server
server:  port: 80
  servlet:    context-path: /
  tomcat:    max-threads: 1000
    
#spring
spring:  datasource:    url: jdbc:mysql:///db_dingcan?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: 
  thymeleaf:    prefix: classpath:/templates/pages/
    suffix: .html
  aop:    proxy-target-class: true
    
#mybatis
mybatis:  configuration:    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:  - classpath:/mapper/sys/*.xml
  
#log
logging:  level:    com.cy: trace
    
#自定义线程池不用
    
    
    
    
    
    
    
    
    
    
    
    
    
    
